#!/usr/bin/env bash
# Configure your domain zone

domain_details () {
    detail=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $detail" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  domain_details "$1" "www"
  domain_details "$1" "lb-01"
  domain_details "$1" "web-01"
  domain_details "$1" "web-02"

elif [ "$#" == 2 ]
then
  domain_details "$1" "$2"
fi
