#!/usr/bin/env bash
# Install haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 435903-web-01	100.25.203.148 check
   server 435903-web-02 54.197.117.164 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
