#!/usr/bin/env bash
#Backup

day=$(date + "%d")
month=$(date + "%m")
year=$(date + "%Y")
name_of_file="$day-$month-%year.tar.gz

mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$file_name" backup.sql
