#!/usr/bin/env bash
# Loop from 0-100
# prints fizz and buzz at multiples of 3 and 5

for x in {1..100}; do
	if (( x%3 == 0 && x%5 == 0 ))
	then
		echo "FizzBuzz"

	elif (( x%3 == 0 ))
	then
		echo "Fizz"

	elif ((  x%5 == 0 ))
	then
		echo "Buzz"
	else 
		echo "$x"
	fi
done 
