#!/usr/bin/env bash
#Displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi

my_string="Best School"
num=0

while [ $num -lt 10 ]; do
	echo "$my_string"
	(( num++ ))
	if [[ $num == 9 ]]
then
		echo "Hi"
	fi
done
