#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20.

num =0;

while [$num -lt 20 ]; do
	echo "$num"
	case "$num" in
		3) echo "bad luck from China";;
		8) echo "bad luck from Japan";;
		16) echo "bad luck from Italy";;
	esac
	(( num++ ))
done
